apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: onlineeventbookinghuzaifanasir
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: 22i1053/booking-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-uri
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rabbitmq-url
        - name: EVENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: event-service-url
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: onlineeventbookinghuzaifanasir
spec:
  selector:
    app: booking-service
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP